#!/bin/bash

rm stardict/*.tar.gz
mkdir -p gismu-cmavo
mkdir -p temp
mkdir -p stardict
mkdir -p kindle
cat xml/jbo.xml | sh/stika-jbo.sh && mv temp/gimste gismu-cmavo/jbo-gimste.html && mv temp/mahoste gismu-cmavo/jbo-mahoste.html && mv temp/gimste.tsv gismu-cmavo/jbo-gimste.tsv && mv temp/mahoste.tsv gismu-cmavo/jbo-mahoste.tsv && mkdir -p stardict/jbo-jbo && sed -f sh/lai-sed5quot < temp/vlaste > stardict/jbo-jbo/jbo-jbo && mv temp/vlaste temp/jbo-jbo.txt && cd stardict/jbo-jbo && tabfile jbo-jbo && rm jbo-jbo && cd - && tar cvfz stardict/jbo-jbo-`date +%Y%m%d`.tar.gz stardict/jbo-jbo && mkdir -p stardict/selmaho-jbo && cp temp/selmaho00tab stardict/selmaho-jbo/selmaho-jbo && cd stardict/selmaho-jbo && tabfile selmaho-jbo && cd - && mv stardict/selmaho-jbo/selmaho-jbo temp/selmaho-jbo.txt && tar cvfz stardict/selmaho-jbo-`date +%Y%m%d`.tar.gz stardict/selmaho-jbo && mv xml/jbo.xml xml/jbo.xm
sh/rafsi.sh && mkdir -p stardict/rafsi-jbo && cp temp/rafsi00tab1 stardict/rafsi-jbo/rafsi-jbo && cd stardict/rafsi-jbo && tabfile rafsi-jbo && cd - && mv stardict/rafsi-jbo/rafsi-jbo temp/rafsi-jbo.txt && tar cvfz stardict/rafsi-jbo-`date +%Y%m%d`.tar.gz stardict/rafsi-jbo
cat xml/eng.xml | sh/stika.sh ; mv temp/gimste gismu-cmavo/eng-gimste.html && mv temp/mahoste gismu-cmavo/eng-mahoste.html && mv temp/gimste.tsv gismu-cmavo/eng-gimste.tsv && mv temp/mahoste.tsv gismu-cmavo/eng-mahoste.tsv && mkdir -p stardict/jbo-eng && sed -f sh/lai-sed5quot < temp/vlaste > stardict/jbo-eng/jbo-eng && mv temp/vlaste temp/jbo-eng.txt && cd stardict/jbo-eng && tabfile jbo-eng && rm jbo-eng && cd - && tar cvfz stardict/jbo-eng-`date +%Y%m%d`.tar.gz stardict/jbo-eng && cat temp/jbo-jbo.txt temp/jbo-eng.txt temp/rafsi-jbo.txt temp/selmaho-jbo.txt > temp/temp && mkdir -p stardict/jbo-eng-rafsi-selmaho && sed -f sh/lai-sed5quot < temp/temp > stardict/jbo-eng-rafsi-selmaho/jbo-eng-rafsi-selmaho && cd stardict/jbo-eng-rafsi-selmaho && tabfile jbo-eng-rafsi-selmaho && cd - && mv stardict/jbo-eng-rafsi-selmaho/jbo-eng-rafsi-selmaho temp/jbo-eng-rafsi-selmaho.txt && tar cvfz stardict/jbo-eng-rafsi-selmaho-`date +%Y%m%d`.tar.gz stardict/jbo-eng-rafsi-selmaho && mv xml/eng.xml xml/eng.xm
cat xml/jpn.xml | sh/stika-jpn-romazi.sh && mv temp/gimste gismu-cmavo/jpn-gimste.html && mv temp/mahoste gismu-cmavo/jpn-mahoste.html && mv temp/gimste.tsv gismu-cmavo/jpn-gimste.tsv && mv temp/mahoste.tsv gismu-cmavo/jpn-mahoste.tsv && mkdir -p stardict/jbo-jpn && sed -f sh/lai-sed5quot < temp/vlaste > stardict/jbo-jpn/jbo-jpn && mv temp/vlaste temp/jbo-jpn.txt && cd stardict/jbo-jpn && tabfile jbo-jpn && rm jbo-jpn && cd - && tar cvfz stardict/jbo-jpn-`date +%Y%m%d`.tar.gz stardict/jbo-jpn && mkdir -p stardict/romazi-jbo && sed -f sh/lai-sed5quot < temp/romazi-jbo.txt > stardict/romazi-jbo/romazi-jbo && cd stardict/romazi-jbo && tabfile romazi-jbo && rm romazi-jbo && cd - && tar cvfz stardict/romazi-jbo-`date +%Y%m%d`.tar.gz stardict/romazi-jbo && cat temp/jbo-jbo.txt temp/jbo-jpn.txt temp/jbo-eng.txt temp/rafsi-jbo.txt temp/selmaho-jbo.txt > temp/temp && mkdir -p stardict/jbo-jpn-eng-rafsi-selmaho && sed -f sh/lai-sed5quot < temp/temp > stardict/jbo-jpn-eng-rafsi-selmaho/jbo-jpn-eng-rafsi-selmaho && cd stardict/jbo-jpn-eng-rafsi-selmaho && tabfile jbo-jpn-eng-rafsi-selmaho && cd - && mv stardict/jbo-jpn-eng-rafsi-selmaho/jbo-jpn-eng-rafsi-selmaho temp/jbo-jpn-eng-rafsi-selmaho.txt && tar cvfz stardict/jbo-jpn-eng-rafsi-selmaho-`date +%Y%m%d`.tar.gz stardict/jbo-jpn-eng-rafsi-selmaho && cat temp/jbo-jbo.txt temp/jbo-jpn.txt temp/jbo-eng.txt temp/rafsi-jbo.txt temp/selmaho-jbo.txt temp/romazi-jbo.txt > temp/temp && mkdir -p stardict/jbo-jpn-eng-rafsi-selmaho-romazi && sed -f sh/lai-sed5quot < temp/temp > stardict/jbo-jpn-eng-rafsi-selmaho-romazi/jbo-jpn-eng-rafsi-selmaho-romazi && cd stardict/jbo-jpn-eng-rafsi-selmaho-romazi && tabfile jbo-jpn-eng-rafsi-selmaho-romazi && cd - && mv stardict/jbo-jpn-eng-rafsi-selmaho-romazi/jbo-jpn-eng-rafsi-selmaho-romazi temp/jbo-jpn-eng-rafsi-selmaho-romazi.txt && tar cvfz stardict/jbo-jpn-eng-rafsi-selmaho-romazi-`date +%Y%m%d`.tar.gz stardict/jbo-jpn-eng-rafsi-selmaho-romazi && mv xml/jpn.xml xml/jpn.xm
for i in xml/*.xml; do cat $i | sh/stika.sh ; mv temp/gimste gismu-cmavo/`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-gimste.html && mv temp/mahoste gismu-cmavo/`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-mahoste.html && mv temp/gimste.tsv gismu-cmavo/`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-gimste.tsv && mv temp/mahoste.tsv gismu-cmavo/`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-mahoste.tsv && mkdir -p stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` && sed -f sh/lai-sed5quot < temp/vlaste > stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` && mv temp/vlaste temp/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`.txt && cd stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` && tabfile jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` && rm jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` && cd - && tar cvfz stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-`date +%Y%m%d`.tar.gz stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'` ; cat temp/jbo-jbo.txt temp/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`.txt temp/jbo-eng.txt temp/rafsi-jbo.txt temp/selmaho-jbo.txt > temp/temp ; mkdir -p stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho ; sed -f sh/lai-sed5quot < temp/temp > stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho ; cd stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho ; tabfile jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho ; cd - ; mv stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho temp/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho.txt ; tar cvfz stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho-`date +%Y%m%d`.tar.gz stardict/jbo-`echo $i | sed -e 's/\.xml//' | sed -e 's/xml\///'`-eng-rafsi-selmaho ; done
rm temp/temp
rename -- .xm .xml xml/*.xm
# cd temp
# cat jbo-jbo.txt jbo-fra.txt jbo-frafacile.txt jbo-jpn.txt jbo-eng.txt rafsi-jbo.txt selmaho-jbo.txt romazi-jbo.txt > jbo-fra-frafacile-jpn-eng-rafsi-selmaho-romazi.txt && sed -f ../sh/lai-sed4 jbo-fra-frafacile-jpn-eng-rafsi-selmaho-romazi.txt > vlaste-kindle && tab2opf.py -utf vlaste-kindle && kindlegen vlaste-kindle.opf
# cd -
# cp temp/vlaste-kindle.mobi kindle/lojban`date +%Y%m%d`.mobi
